version: '3.3'

networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  web:
    depends_on:
      - database
    image: nginx
    container_name: 'nginx'
    restart: always
    networks:
      proxy-network:
        ipv4_address: 172.20.0.2
    ports:
      - '80:80'

  database:
    image: mysql:8.0
    container_name: 'mysql8'
    restart: always
    ports:
      - '3366:3306'
    expose:
      - '3306'
    networks:
      proxy-network:
        ipv4_address: 172.20.0.3
    volumes:
      - ./mysql-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ROOTpassword'
    dns:
    - 8.8.8.8
    dns_search:
    - dc1.example.com
    extra_hosts:
    - "somehost:172.20.20.1"
    - "otherhost:172.20.20.2"
